# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-10-15 04:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAuth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='pic',
            field=models.ImageField(default='pic_folder/index.png', upload_to='pic_folder/'),
        ),
    ]
