# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-10-15 07:13
from __future__ import unicode_literals

import UserAuth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAuth', '0004_auto_20191015_0705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='pic',
            field=models.ImageField(default='Profile/index.png', upload_to=UserAuth.models.upload_profile_pic_path),
        ),
    ]
